---
title: "Parent–Child Relationship and Learning Engagement"
author: "wmj"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo     = FALSE,
    warning  = FALSE, 
    message  = FALSE,
    fig.asp  = 0.618,
    dpi      = 300
)
options(digits = 3)
```



```{r}
library(tidyverse)
library(lavaan)

rawdata <- readxl::read_excel("./rawdata/Table 1.XLS")
rawdata %>% sjPlot::view_df()
```


```{r, fig.width=10}
rawdata %>% 
  dplyr::select(-c(1:3)) %>% 
  psych::cor.plot()
```

# Sampling and Data Collection

```{r}
rawdata %>% 
  count(gender) %>% 
  mutate(p = n/sum(n)) %>% 
  mutate(prop = scales::percent(p))
```


```{r}
rawdata %>% 
  count(Grade) %>% 
  mutate(p = n/sum(n)) %>% 
  mutate(prop = scales::percent(p))
```


```{r}
rawdata %>% 
  count(place) %>% 
  mutate(p = n/sum(n)) %>% 
  mutate(prop = scales::percent(p))
```

偷懒的办法

```{r}
library(gtsummary)

rawdata %>% 
  select(gender, Grade, place) %>% 
  gtsummary::tbl_summary()
```



# Confirmatory Factor Analysis

Confirmatory factor analysis (CFA) was performed for each variable 
```{r}
m_PCR <- '
  PCR   =~ PCR1 + PCR2 + PCR3 + PCR4 + PCR5 + PCR6
'

m_LE <- '
  LE    =~ LE1 + LE2 + LE3 + LE4
'


m_ASE <- '
  ASE   =~ ASE1 + ASE2 + ASE3 + ASE4 + ASE5 
'

m_LM <- '
  LM    =~ LM1 + LM2 + LM3 + LM4
'

lst(m_PCR, m_LE, m_ASE, m_LM) %>% 
  purrr::map( ~cfa(.x, data = rawdata) ) %>% 
  lavaanExtra::nice_fit(nice_table = TRUE)
```

## Table 2
```{r}
cfamodel <- '

  PCR   =~ PCR1 + PCR2 + PCR3 + PCR4 + PCR5 + PCR6
  LE    =~ LE1 + LE2 + LE3 + LE4
  ASE   =~ ASE1 + ASE2 + ASE3 + ASE4 + ASE5 
  LM    =~ LM1 + LM2 + LM3 + LM4

'

fit_cfa <- cfa(cfamodel, 
               data      = rawdata,
               estimator = "MLR", 
               mimic     = "Mplus")
```


```{r}
alpha <- fit_cfa %>% semTools::reliability()   # Cronbach alpha
CR    <- fit_cfa %>% semTools::compRelSEM()    # CR
AVE   <- fit_cfa %>% semTools::AVE()           # AVE 

dd <- tibble(
  name  = names(CR),
  alpha = alpha[1,],
  CR    = CR,
  AVE   = AVE
) 
```





```{r}
tb2 <- fit_cfa %>% 
  parameterestimates(standardized = TRUE) %>% 
  filter(op == "=~") %>% 
  mutate(pvalue = gtools::stars.pval(pvalue)) %>% 
  select(lhs, rhs, est, se, z, pvalue, std.all) %>% 
  left_join(dd, by = join_by(lhs == name)) %>% 
  flextable::flextable() %>% 
  flextable::merge_v(j = c("lhs", "alpha", "CR", "AVE")) %>% 
  flextable::valign(j = "lhs", valign = "top") %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::autofit()
```





```{r, eval=FALSE}
tab2 %>% 
  flextable::save_as_docx(path = "ppp.docx")
```






## Table 3 

The discriminate validity test of latent variables.

```{r}
m <- lavInspect(fit_cfa, what = "cor.lv") 
order <- c("PCR", "LM", "ASE", "LE")
m <- m[order, order]
m[upper.tri(m)] <- NA
diag(m) <- semTools::AVE(fit_cfa) %>% sqrt()

m %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(" " = rowname) %>% 
  flextable::flextable() %>%
  flextable::colformat_double(digits = 3) %>% 
  flextable::autofit() 
```


or
```{r}
AVE <- fit_cfa %>% semTools::AVE()  

fit_cfa %>% 
  lavaan::lavInspect(what = "cor.lv") %>% 
  corrr::as_cordf(diagonal = sqrt(AVE)) %>% 
  corrr::shave() %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::autofit()
```




## Table 4
```{r}
library(lavaanExtra)
fit_cfa %>% 
  lavaanExtra::nice_fit(nice_table = TRUE)
```




## Table 5

```{r}
model <- '

   PCR   =~ PCR1 + PCR2 + PCR3 + PCR4 + PCR5 + PCR6
   LE    =~ LE1 + LE2 + LE3 + LE4
   ASE   =~ ASE1 + ASE2 + ASE3 + ASE4 + ASE5 
   LM    =~ LM1 + LM2 + LM3 + LM4

   LM    ~  H2*PCR  
   ASE   ~  H5*PCR + H6*LM
   LE    ~  H1*PCR + H3*LM + H7*ASE

   DistalIE     := H2*H6*H7
   LMIE         := H2*H3
   ASEIE        := H5*H7
   TIE          := DistalIE + LMIE + ASEIE
   DE           := H1
   TE           := TIE + DE
   
   LMDIEdiff    := LMIE  - DistalIE
   ASEDIEdiff   := ASEIE - DistalIE
   LMASEdiff    := LMIE  - ASEIE
   
   P1           := DistalIE/TIE
   P2           := LMIE/TIE
   P3           := ASEIE/TIE
   P4           := TIE/TE
   P5           := DE/TE

'


fit_sem <- sem(model, 
               data      = rawdata, 
               se        = "bootstrap",
               bootstrap = 5000,
               mimic     = "Mplus"
               )
```







```{r}
fit_sem %>%  
  parameterEstimates(standardized = TRUE) %>% 
  filter(op %in% c("~")) %>%  
  filter(str_detect(label, "^H")) %>% 
  mutate(" " = gtools::stars.pval(pvalue), .after = pvalue) %>%
  arrange(label) %>% 
  flextable::flextable() %>% 
  flextable::autofit() %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::colformat_double(digits = 3)
```

我们得到的结论，和图中的系数一样，但和表5中不同




## Table 6
Direct, indirect, and total effects of the hypothesized model.

```{r}
fit_sem %>%  
  parameterEstimates(standardized = TRUE) %>% 
  filter(op %in% c(":=")) %>%  
  select(label, est, se, z, pvalue, ci.lower, ci.upper, std.all) %>% 
  flextable::flextable() %>% 
  flextable::autofit() %>% 
  flextable::color(j = "est", color = "red") %>% 
  flextable::colformat_double(digits = 3)
```